Repository openshift/os, pull requests merged in 2018-08, with the labels that each got.

#193 jenkins/cloud: Name images with version number and better suffix
  Jenkinsfile.cloud
Labels: lgtm, size/M

#194 Set version to 4
  Dockerfile
  Dockerfile.rollup
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#197 pipelines: skip the repo checkout
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#196 jenkins/treecompose: Use `rpm-ostree compose tree` directly
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#198 cloud.ks: Delete lots of cruft
  cloud.ks
Labels: lgtm, size/M

#195 rdgo: remove uncessary install steps
  Jenkinsfile.rdgo
Labels: lgtm, size/S

#200 Make /tmp be tmpfs by default
  cloud.ks
  compose-post.sh
  host.yaml
Labels: lgtm, size/S

#199 ks: Add `rw` to default kargs
  cloud.ks
Labels: lgtm, size/XS

#202 jenkins/treecompose: Rename current oscontainer to `os-maipo`
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#203 jenkins/cloud: Run a basic (15 second) kola rhcos.basic test
  Jenkinsfile.cloud
Labels: lgtm, size/S

#207 Fix rdgo location
  Dockerfile
  rhcos-continuous.repo
Labels: lgtm, size/M

#208 jenkins: Define a common prelude
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#213 jenkins/treecompose: Just use ${WORKSPACE} rather than -v /srv
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#214 jenkins: Read ref and version from manifest file
  Jenkinsfile.cloud
  Jenkinsfile.treecompose
  host.yaml
Labels: lgtm, size/S

#215 utils: Add helper to run assembler
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
  pipeline-utils.groovy
Labels: lgtm, size/S

#217 treecompose: move DRY_RUN check to even later stage
  Jenkinsfile.treecompose
Labels: lgtm, size/M

#218 treecompose: use correct location of Dockerfile
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#219 treecompose: correct location of repo in Dockerfile
  Dockerfile.rollup
Labels: lgtm, size/XS

#221 cloud: read host.yaml after SCM checkout
  Jenkinsfile.cloud
Labels: lgtm

#220 Do backups asynchronously
  Jenkinsfile.backup
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
  pipeline-utils.groovy
Labels: lgtm, size/M

#223 rdgo: don't sync out broken overlay.yml symlink
  Jenkinsfile.rdgo
Labels: lgtm, size/XS

#226 cloud: archive freshly built qcow2
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#228 Jenkinsfile.cloud: +8G the qemu qcow2
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#210 jenkins: Redirect pkg diff to file
  Jenkinsfile.treecompose
Labels: lgtm, size/M

#231 remove extra quote
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#232 Jenkinsfile.cloud: fix image archive
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#234 treecompose: Read manifest after checkout
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#235 manifest: Use boot_location: new
  host.yaml
Labels: lgtm, size/XS

#237 Split host into base + maipo
  Jenkinsfile.treecompose
  Makefile
  host-base.yaml
  host-maipo.yaml
Labels: lgtm, size/M

#238 jenkins: Consistently use rhcos jenkins
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#240 jenkins/cloud: Fix manifest reference
  Jenkinsfile.cloud
  compose-post.sh
Labels: lgtm, size/XS

#241 jenkins: Automatically make jobs not starting with rhcos- devel
  pipeline-utils.groovy
Labels: lgtm, size/XS

#244 jenkins: Refactor treecompose oscontainer pull to script
  Jenkinsfile.treecompose
  scripts/pull-mount-oscontainer
Labels: lgtm, size/M

#246 Remove vestigal CentOS base usage
  RPM-GPG-KEY-CentOS-7
  centos.repo
  contrib/host-origin.json
Labels: lgtm, size/L

#248 README: Fix the README-development link
  README.md
Labels: lgtm, retest-not-required-docs-only, size/XS

#247 manifest: Explicitly set machineid-compat: false at toplevel
  host-maipo.yaml
Labels: lgtm, size/XS

#249 jenkins: Lower more treecompose logic to shell
  Jenkinsfile.treecompose
  scripts/run-treecompose
Labels: lgtm, size/M

#251 jenkins/treecompse: Skip change detection logic for DRY_RUN
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#245 rhel.repo: Make use of distribution-gpg-keys
  Jenkinsfile.treecompose
  RPM-GPG-KEY-redhat-release
  rhel.repo
Labels: lgtm, size/M

#250 Add RHCOS kola testing on aws
  Jenkinsfile.aws-test
  Jenkinsfile.cloud
  pipeline-utils.groovy
Labels: lgtm, size/L

#253 jenkins: Override any entrypoint set for the assembler container
  pipeline-utils.groovy
Labels: lgtm, size/XS

#254 Fix wrong aws json location
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#255 treecompose: Drop some dead code
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#256 Fix file rsync flag
  pipeline-utils.groovy
Labels: lgtm, size/XS

#257 jenkins/treecompose: Archive composeMeta JSON
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#261 Speed up aws tests
  Jenkinsfile.aws-test
Labels: lgtm, size/XS

#263 jenkins/ootpa: Sync changes from maipo job
  Jenkinsfile.treecompose-ootpa
Labels: lgtm, size/XS

#264 host: add coreos-metadata binary and service
  coreos-metadata.repo
  host-base.yaml
  host-maipo.yaml
Labels: lgtm, size/S
