Repository openshift/os, pull requests merged in 2018-07, with the labels that each got.

#149 cloud.ks: Add $coreos_firstboot karg, create /boot/coreos-firstboot
  cloud.ks
Labels: lgtm, size/XS

#151 overlay: Rebuild cri-o from Fedora dist-git, not git master
  overlay.yml
Labels: lgtm, size/XS

#154 Treecompose oscontainer trigger
  Jenkinsfile.oscontainer
  Jenkinsfile.treecompose
  pipeline-utils.groovy
Labels: lgtm, size/S

#153 Dockerfile: Fix nginx root
  Dockerfile.rollup.in
  README.md
  index.html
  rollup.sh
Labels: lgtm, size/S

#156 jenkins/cloud: Dedup dependency package list
  Jenkinsfile.cloud
Labels: lgtm, size/S

#155 pipeline-utils: Group secret and not-secret values
  pipeline-utils.groovy
Labels: lgtm, size/S

#160 Move rdgo bits to rdgo/ subdirectory
  Jenkinsfile.rdgo
  rdgo/DigiCertHighAssuranceEVRootCA.crt
  rdgo/centos-7-and-extras-x86_64.cfg
  rdgo/overlay.yml
Labels: lgtm, size/XS

#161 Makefile: Use download.fp.org for mirrors
  Makefile
  README-development.md
Labels: lgtm, size/M

#164 host: Remove subman
  host.yaml
Labels: lgtm, size/XS

#163 jenkins/treecompose: Maintain content in container
  Dockerfile.rollup
  Jenkinsfile.oscontainer
  Jenkinsfile.treecompose
  rollup.sh
Labels: lgtm, size/L

#166 treecompose: Use `G_DEBUG=fatal-warnings`
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#167 jenkins/treecompose: Fix prune ordering
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#168 jenkins/treecompose: Fix cleanup ordering
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#172 jenkins/cloud,rdgo: Sync cloud images and rdgo into rhcos bucket
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
Labels: lgtm, size/S

#174 jenkins/cloud: Remove rpm-ostree db diff
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#175 Makefile: Support include from out-of-tree
  Makefile
Labels: lgtm, size/XS

#176 host: Install all languages
  host.yaml
Labels: lgtm, size/XS

#158 cloud.ks: Add tty0 console output for ignition logging
  cloud.ks
Labels: lgtm, size/XS

#181 oscontainer: store commit + version in labels
  Dockerfile
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#182 oscontainer: actually store commit + version in labels
  Dockerfile.rollup
Labels: lgtm, size/XS

#185 cloud: stop using version strings for comparison
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#186 treecompose: define the ostree_version variable
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#187 oscontainer: workaround podman label bug
  Dockerfile
  Dockerfile.rollup
Labels: lgtm, size/S

#188 jenkins/treecompose: Only trigger cloud on changes
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#189 oscontainer: remove spaces from image labels
  Dockerfile
  Dockerfile.rollup
Labels: lgtm, size/S
