Repository openshift/os, pull requests merged in 2018-10, with the labels that each got.

#308 adopt `buildmaster` and `alpha` tags for oscontainer
  Jenkinsfile.aws-test
  Jenkinsfile.treecompose
Labels: lgtm, size/M

#333 utils: don't nuke root dir in `prep_container_storage()`
  pipeline-utils.groovy
Labels: lgtm, size/XS

#332 rollup: Also add com.coreos.ostree-commit label
  Dockerfile.rollup
Labels: lgtm, size/XS

#335 jenkins: Remove ootpa build for now
  Jenkinsfile.treecompose-ootpa
Labels: lgtm, size/L

#334 Fix podman login in various ways
  Jenkinsfile.aws-test
  Jenkinsfile.treecompose
  pipeline-utils.groovy
  scripts/pull-mount-oscontainer
Labels: lgtm, size/S

#336 .gitignore: Empty out
  .gitignore
Labels: lgtm, size/XS

#337 treecompose: pass correct args to `pull-mount-oscontainer`
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#330 Copy tested AMI to more regions
  Jenkinsfile.aws-test
  scripts/ami-copy-regions
Labels: lgtm, size/L

#341 scripts/ami-copy-regions: Try waiting on all AMIs
  scripts/ami-copy-regions
Labels: lgtm, size/M

#327 treecompose: use `atomic-openshift-*` packages
  generate-openshift-repo
  host-base.yaml
  host-maipo.yaml
Labels: lgtm, size/S

#343 jenkins: use `oc` for image tagging
  Jenkinsfile.aws-test
  Jenkinsfile.treecompose
  pipeline-utils.groovy
Labels: lgtm, size/M

#344 ami-copy-regions: Also include origin region (us-east-1)
  scripts/ami-copy-regions
Labels: lgtm, size/XS

#345 utils: fix quoting mistakes
  pipeline-utils.groovy
Labels: lgtm, size/XS

#346 Revert kubelet switch
  generate-openshift-repo
  host-base.yaml
  host-maipo.yaml
Labels: lgtm, size/S

#348 jenkins: revert to `skopeo copy` for tagging
  Jenkinsfile.aws-test
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#350 Revert "jenkins: revert to `skopeo copy` for tagging"
  Jenkinsfile.aws-test
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#355 host-base: Drop ref
  host-base.yaml
Labels: lgtm, size/XS

#359 RELEASE: Add RELEASE.txt file for instructions
  RELEASE.txt
Labels: lgtm, size/S

#357 maipo: use correct, up-to-date repo
  maipo.repo
Labels: lgtm, size/XS

#363 Remove rdgo bits here
  Jenkinsfile.rdgo
  rdgo/DigiCertHighAssuranceEVRootCA.crt
  rdgo/centos-7-and-extras-x86_64.cfg
  rdgo/overlay.yml
Labels: lgtm, size/L
