Repository openshift/os, pull requests merged in 2018-05, with the labels that each got.

#2 Make CentOS a build-time option again
  Dockerfile
  README.md
  RPM-GPG-KEY-CentOS-7
  centos.repo
  host-base.json
  host-origin.json
  host-rhcos.json
  rhel.repo
Labels: lgtm, size/L

#3 Add .prow.sh script
  .prow.sh
Labels: lgtm, size/S

#4 Use Makefile to separate responsibilities a bit more
  .prow.sh
  Makefile
  README.md
Labels: lgtm, size/S

#5 Add Jenkinsfile compose pipeline
  Jenkinsfile
  host-base.json
  host-origin.json
  host-rhcos.json
  rhel.repo
Labels: lgtm, size/L

#6 Initial overlay
  .gitignore
  DigiCertHighAssuranceEVRootCA.crt
  overlay.yml
Labels: enhancement, lgtm, size/M

#7 rdgo: build crio
  overlay.yml
Labels: lgtm, size/XS

#8 overlay.yml: Add origin to be one of the packages
  overlay.yml
Labels: lgtm, size/XS

#10 Add cloud image pipeline
  Jenkinsfile.cloud
  Jenkinsfile.treecompose
  cloud.ks
  rhcos.tdl
Labels: lgtm, size/L

#11 rdgo: Add openshift repo and required mock packages
  .gitignore
  Makefile
  generate-openshift-repo
  host-base.json
  overlay.yml
Labels: enhancement, lgtm, size/S

#13 treecompose: Generate openshift repo before composing
  Jenkinsfile.treecompose
  Makefile
  generate-openshift-repo
  host-base.json
  openshift.repo
Labels: lgtm, size/S

#15 rdgo: Add ignition via fake distgit
  host-base.json
  overlay.yml
Labels: lgtm, size/S

#16 Add a rdgo pipeline
  Jenkinsfile.rdgo
Labels: lgtm, size/M

#19 rdgo: Minor typo fix
  Jenkinsfile.rdgo
Labels: lgtm, size/XS

#20 Add credentials to sync out
  Jenkinsfile.rdgo
Labels: lgtm, size/S

#21 cloud.ks: Switch to RHELAH kickstart
  cloud.ks
Labels: lgtm, size/L

#23 base: Enable ostree-remount
  host-base.json
Labels: lgtm, size/XS

#27 rdgo: Publish repo to S3
  Jenkinsfile.rdgo
  host-base.json
  rhcos-continuous.repo
Labels: lgtm, size/S

#26 host: Add origin* packages
  host-base.json
Labels: lgtm, size/XS

#28 host-base.json: Add cri-o
  host-base.json
Labels: lgtm, size/XS

#32 Build cni plugins
  overlay.yml
Labels: bug, lgtm, size/XS

#33 prow: Stop building container for now
  .prow.sh
Labels: lgtm, size/XS

#31 Dockerfile: Make nginx work again
  Dockerfile
Labels: lgtm, size/XS

#35 ci: Re-enable container building on PRs
  .prow.sh
Labels: lgtm, size/XS

#36 Jenkinsfile: Add descriptions
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#38 treecompose: Write commitid to workspace too
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#39 Default to rhcos, move host-origin to contrib/
  .prow.sh
  Jenkinsfile.cloud
  Jenkinsfile.treecompose
  Makefile
  README.md
  contrib/host-origin.json
  host-base.json
Labels: lgtm, size/M

#40 treecompose: Add db-diff
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#41 treecompose: Add missing --repo arg
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#42 treecompose: Trim commit string
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#34 Add redhat-release-coreos
  host-base.json
  host-rhcos.json
  overlay.yml
Labels: lgtm, size/XS

#43 cloud: Minor prep patches
  Jenkinsfile.cloud
Labels: lgtm, size/S

#45 cloud: add provision + metadata stages
  Jenkinsfile.cloud
Labels: lgtm, size/M

#47 Dockerfile: Do a repo-refresh
  Dockerfile
Labels: lgtm, size/XS

#46 cloud: fix sha256sum generation
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#49 cloud: escape Groovy's string interpolation
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#44 cloud: Generate AMIs
  Jenkinsfile.cloud
  rhcos.tdl
Labels: lgtm, size/M

#51 rdgo: Force cri-o to 1.10.x
  overlay.yml
Labels: lgtm, size/XS

#50 cloud: Add more tags to AMI and snapshot
  Jenkinsfile.cloud
  Jenkinsfile.treecompose
Labels: lgtm, size/L

#53 treecompose: Fix bad comment string
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#52 Convert to YAML definition, use coreos-assembler
  Jenkinsfile.treecompose
  host-base.json
  host-rhcos.json
  host.yaml
Labels: lgtm, size/L

#54 treecompose: Fix provision/check ordering
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#55 manifest: Add podman
  host.yaml
Labels: lgtm, size/XS

#57 cloud: Fix file path and use coreos-assembler container
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#58 jenkins/rdgo: Archive rdgo artifacts
  Jenkinsfile.rdgo
Labels: lgtm, size/XS

#60 cloud: Run `docker pull` on the node, not master
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#62 jenkins/rdgo: Allow empty artifacts
  Jenkinsfile.rdgo
Labels: lgtm, size/XS

#65 Dockerfile,Makefile: Use coreos-assembler
  Dockerfile
  Makefile
Labels: lgtm, size/S

#61 Add a "rollup" task that does ostreerepo → container
  Dockerfile
  Dockerfile.rollup.in
  Jenkinsfile.oscontainer
  rollup.sh
Labels: lgtm, size/M

#67 cloud: Fix AMI upload regression
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#64 Add pipeline-utils.groovy local lib
  Jenkinsfile.cloud
  Jenkinsfile.oscontainer
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
  pipeline-utils.groovy
Labels: lgtm, size/L
