Repository openshift/os, pull requests merged in 2018-09, with the labels that each got.

#268 jenkins: Use coreos-assembler:alpha tag
  pipeline-utils.groovy
Labels: lgtm, size/XS

#260 jenkins/cloud: Change version schema, add+use `meta.json`
  Jenkinsfile.cloud
Labels: lgtm, size/M

#270 rhel.repo: Switch to 7Server
  rhel.repo
Labels: bug, kind/bug, lgtm, size/XS

#272 jenkins/cloud: Fix change detection
  Jenkinsfile.cloud
Labels: lgtm, size/S

#273 treecompose: use 'ceph-tools-2' + 'glusterfs' repo
  host-maipo.yaml
  rhel.repo
Labels: lgtm, size/S

#274 jenkins/cloud: Fix image genver logic
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#276 ootpa: Add coreos-metadata repo
  host-ootpa.yaml
Labels: lgtm, size/XS

#277 Add an OWNERS file
  OWNERS
Labels: lgtm, size/S

#267 Drop tuned
  Makefile
  host-maipo.yaml
Labels: lgtm, size/XS, ¯\_(ツ)_/¯

#278 Rename maipo repos to use that name
  host-maipo.yaml
  maipo.repo
Labels: lgtm, size/S

#279 maipo: Delete lua interpreters
  host-maipo.yaml
Labels: lgtm, size/XS

#280 ci: Also syntax check YAML files
  .prow.sh
  Makefile
Labels: lgtm, size/XS

#282 ci: Adapt for coreos-assembler
  .prow.sh
  Makefile
Labels: lgtm, size/XS

#283 Drop docker from compose
  host-maipo.yaml
  rdgo/overlay.yml
Labels: lgtm, size/XS

#288 Switch to faster moving cri-o rpms
  Jenkinsfile.treecompose
  cri-o-tested.repo
  host-base.yaml
  host-maipo.yaml
  pipeline-utils.groovy
  rdgo/overlay.yml
Labels: lgtm, size/M

#290 Revert revert: Remove docker
  host-maipo.yaml
  rdgo/overlay.yml
Labels: lgtm, size/XS

#292 jenkins: Create a prepare_configuration() helper
  Jenkinsfile.treecompose
  Jenkinsfile.treecompose-ootpa
  pipeline-utils.groovy
Labels: lgtm, size/M

#294 Drop LVM, use custom growpart wrapper
  cloud.ks
  compose-post.sh
Labels: lgtm, size/M

#295 cloud: Switch to use sda2 for root
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#297 jenkins/cloud: Drop qcow2-to-vagrant
  Jenkinsfile.cloud
Labels: lgtm, size/S

#300 cloud: Specify eth0 for now for ip= line to ensure networking
  cloud.ks
Labels: lgtm, size/XS

#302 maipo: Add some comments around repo origins
  host-maipo.yaml
Labels: lgtm, size/S

#303 cloud: fix archive of qcow2 image
  Jenkinsfile.cloud
Labels: lgtm, size/S

#305 rdgo: Move pivot to openshift namespace
  rdgo/overlay.yml
Labels: enhancement, lgtm, size/XS

#304 jenkins: Make RHCOS AMI Public
  Jenkinsfile.aws-test
Labels: lgtm, size/XS

#306 jenkins: Add Slack notifications for job status changes
  Jenkinsfile.aws-test
  Jenkinsfile.cloud
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
  Jenkinsfile.treecompose-ootpa
  pipeline-utils.groovy
Labels: lgtm, size/M

#310 jenkins: List OS version in AMI test job
  Jenkinsfile.aws-test
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#315 maipo: Revert to released content
  maipo.repo
Labels: lgtm, size/S

#313 Push tested ami json to public aws bucket
  Jenkinsfile.aws-test
  pipeline-utils.groovy
Labels: lgtm, size/S

#309 pipeline-utils: add `registry_login()` and `prep_container_storage()`
  pipeline-utils.groovy
Labels: lgtm, size/S

#316 host: Switch to inline `postprocess` element
  compose-post.sh
  host-base.yaml
  host-maipo.yaml
Labels: lgtm, size/L

#317 manifest: Drop duplicates from host-base now that rpm-ostree updated
  host-maipo.yaml
  host-ootpa.yaml
Labels: lgtm, size/S

#320 host-base: Run xfs_growfs after growpart
  host-base.yaml
Labels: lgtm, size/S

#312 aws-test: Drop need for parameters, just use latest/
  Jenkinsfile.aws-test
  Jenkinsfile.cloud
  pipeline-utils.groovy
Labels: lgtm, size/M

#322 aws-test: Fix create-tags syntax
  Jenkinsfile.aws-test
Labels: lgtm, size/XS

#321 host-base.yaml: Add systemd-journal-gateway
  host-base.yaml
Labels: enhancement, lgtm, size/XS

#323 treecompose: properly record sha256sum
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#324 aws-test: Fix JSON filename passed to aws
  Jenkinsfile.aws-test
Labels: lgtm, size/XS

#326 pipeline: don't send Slack update for dev pipelines
  pipeline-utils.groovy
Labels: lgtm, size/XS

#329 cloud: Name AMIs with version, not commit
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#331 Add toolbox package to rdgo
  host-base.yaml
  rdgo/overlay.yml
Labels: lgtm, size/XS
