Repository openshift/os, pull requests merged in 2018-06, with the labels that each got.

#74 container: Fix locations, tweak README.md
  Dockerfile
  README.md
  index.html
  nginx.conf
Labels: lgtm, size/M

#75 Attempt to get ignition working in stream
  cloud.ks
  host.yaml
  overlay.yml
Labels: enhancement, lgtm, size/S

#76 Remove harcoding of EC2 target
  cloud.ks
Labels: lgtm, size/XS

#81 Add developmentPipeline, DRY_RUN
  Jenkinsfile.cloud
  Jenkinsfile.oscontainer
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
  pipeline-utils.groovy
Labels: lgtm, size/M

#83 Jenkinsfile.cloud: Use qcow2-to-vagrant to make vagrant-libvirt box
  Jenkinsfile.cloud
Labels: lgtm, size/M

#84 Treecompose fixes
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#87 cloud: Fix vagrant box to use qcow2
  Jenkinsfile.cloud
Labels: lgtm, size/S

#89 Jenkinsfile.cloud: Write AMI json to images directory
  Jenkinsfile.cloud
Labels: lgtm, size/M

#92 jenkins: Add triggers between jobs
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#90 jenkins/treecompose: Add version to build description too
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#93 jenkins/cloud: Fix missed out.txt reference for AMI json
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#91 cloud/treecompose: Log more when doing dry runs
  Jenkinsfile.cloud
  Jenkinsfile.treecompose
Labels: lgtm, size/S

#97 jenkins/treecompose: Do expand variables for label
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#100 Don't wait for triggered jobs to finish
  Jenkinsfile.rdgo
  Jenkinsfile.treecompose
Labels: lgtm, size/XS

#98 Add pivot in rdgo
  overlay.yml
Labels: lgtm, size/XS

#103 Include pivot
  README.md
  host.yaml
Labels: enhancement, lgtm, size/S

#109 cloud: add in 'core' user for now
  cloud.ks
Labels: lgtm, size/XS

#113 cloud: Fixes for ec2 stamping
  Jenkinsfile.cloud
  scripts/coreos-oemid
Labels: lgtm, size/S

#115 host: drop kexec-tools
  host.yaml
Labels: lgtm, size/XS

#110 cloud.ks: Add core user to some groups
  cloud.ks
  host.yaml
Labels: lgtm, size/XS

#118 compose-post: Remove network.service
  compose-post.sh
Labels: lgtm, size/XS

#119 Makefile: s/coreos-assembler/rpm-ostree compose tree/
  Dockerfile
  Makefile
Labels: lgtm, size/XS

#120 Remove cloud-init
  cloud.ks
  host.yaml
Labels: lgtm, size/XS

#122 Add sudo group
  cloud.ks
  compose-post.sh
  group
  host.yaml
Labels: lgtm, size/S

#107 Initial how to build info and Make targets
  Makefile
  README-development.md
Labels: help wanted, kind/documentation, lgtm, size/M

#127 rdgo: Build cri-tools
  overlay.yml
Labels: enhancement, lgtm, size/XS

#128 host.yaml: Add cri-tools
  host.yaml
Labels: enhancement, lgtm, size/XS

#129 scripts: don't hardcode path to bash
  scripts/coreos-oemid
Labels: lgtm, size/XS

#131 cloud: Share AMI with new OpenShift AWS CI account
  Jenkinsfile.cloud
  pipeline-utils.groovy
Labels: lgtm, size/S

#130 Jenkinsfile.cloud: start producing QEMU image
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#132 manifest: Explicitly set tmp-is-dir: false
  host.yaml
Labels: lgtm, size/XS

#134 host: Explicitly include container-storage-setup and growpart
  host.yaml
Labels: lgtm, size/XS

#136 cloud: Fix sha256sum generation
  Jenkinsfile.cloud
Labels: lgtm, size/XS

#138 jenkins: Move container to registry.svc.ci.openshift.org/rhcos/os:latest
  Jenkinsfile.oscontainer
Labels: lgtm, size/S

#139 Follow-up creds fix for oscontainer
  pipeline-utils.groovy
Labels: lgtm, size/XS

#135 Fix ConditionFirstBoot= by removing /etc/machine-id
  compose-post.sh
  host.yaml
Labels: lgtm, size/S

#140 compose-post: Remove readahead
  compose-post.sh
Labels: lgtm, size/XS

#141 RFC: Add strace to the host
  host.yaml
Labels: lgtm, size/XS

#142 post: Tweak /etc/motd
  compose-post.sh
Labels: lgtm, size/S
