Repository openshift/os, pull requests merged in 2021-10, with the labels that each got.

#641 Bug 2009465: Revert "Revert "Revert "manifest: force container-selinux from OSE repo"""
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#643 Bug 2009840: extensions: make virt:av module and advanced virt repo specific to kata
  extensions.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#633 manifest: use default VMWare driver config in initramfs
  manifest.yaml
Labels: lgtm, approved

#644 Bug 2009842: [release-4.9] extensions: make virt:av module and advanced virt repo specific to kata
  extensions.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#642 Bug 2009467: Revert "Revert "Revert "manifest: force container-selinux from OSE repo"""
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#640 Bug 2009652: [release-4.9] Enable multipath.day1 test again for s390x
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/severity-medium
