Repository openshift/os, pull requests merged in 2021-09, with the labels that each got.

#611 image: Switch to `ostree-format: oci`
  image.yaml
Labels: lgtm, approved

#613 Revert "image: Switch to `ostree-format: oci`"
  image.yaml
Labels: lgtm, approved

#612 ci: Run upgrade tests and all kola tests (--parallel 2)
  ci/prow-build-test-qemu.sh
Labels: lgtm, approved

#616 manifest: force container-selinux from OSE repo
  manifest.yaml
Labels: approved

#618 40rhcos-fips: drop redundant zipl run with coreos-installer 0.10.0
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/module-setup.sh
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.sh
Labels: lgtm, approved

#621 Revert "manifest: force container-selinux from OSE repo"
  manifest.yaml
Labels: lgtm, approved

#624 Revert "Revert "manifest: force container-selinux from OSE repo""
  manifest.yaml
Labels: lgtm, approved

#623 manifest: bump version strings to 4.10
  manifest.yaml
Labels: lgtm, approved

#629 FAQ: Note that we expose some key package versions via metadata
  docs/faq.md
Labels: lgtm, approved

#619 image: Switch to `ostree-format: oci`
  image.yaml
Labels: lgtm, approved

#622 Bug 2003743: Revert "overaly: Keep /boot RW when kdump is enabled"
  overlay.d/12kdump
  tests/kola/kdump/test.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#632 Bug 2003743: tests/kdump: Only run on x86_64 & aarch64
  tests/kola/kdump/test.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#634 Bug 2006432: [release-4.9] Revert "overaly: Keep /boot RW when kdump is enabled"
  overlay.d/12kdump
  tests/kola/kdump/test.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#635 test: add test to check rhaos package versions
  tests/kola/misc-ro/misc-ro.sh
Labels: lgtm, approved

#639 Enable multipath.day1 test again for s390x
  kola-denylist.yaml
Labels: lgtm, approved

#636 [release-4.9] test: add test to check rhaos package versions
  tests/kola/misc-ro/misc-ro.sh
Labels: lgtm, approved
