Repository openshift/os, pull requests merged in 2021-07, with the labels that each got.

#575 OWNERS: remove arithx
  OWNERS
Labels: approved, lgtm

#580 rhcos-afterburn-checkin: wait for Ignition fetch and kargs stages
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: approved, lgtm

#581 rhcos-afterburn: Add original downstream commit message
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: approved, lgtm

#577 manifest: Explicitly set rpmdb: bdb
  manifest.yaml
Labels: approved, lgtm

#584 overlay: add empty statoverride files in all overlays
  overlay.d/05rhcos/statoverride
  overlay.d/06gcp-routes/statoverride
  overlay.d/15rhcos-logrotate/statoverride
  overlay.d/15rhcos-tuned-bits/statoverride
  overlay.d/21dhcp-chrony/statoverride
  overlay.d/25rhcos-azure-udev-rules/statoverride
Labels: approved, lgtm

#583 Bug 1982003: [4.7] rhcos-afterburn-checkin: wait for Ignition fetch stage
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: approved, bugzilla/severity-medium, lgtm

#582 Bug 1982002: [4.8] rhcos-afterburn-checkin: wait for Ignition fetch stage
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: approved, bugzilla/severity-medium, lgtm

#586 ci: add debug information about cosa/rpm-ostree
  ci/build-test-qemu.sh
Labels: approved, lgtm

#585 manifest.yaml: use `rpmdb: bdb`
  manifest.yaml
Labels: approved, lgtm

#590 gitignore: add `/*.repo`
  .gitignore
Labels: approved, lgtm

#591 rhcos-packages: Add bootupd
  rhcos-packages.yaml
Labels: approved, lgtm

#574 overlay: combine reboots for FIPS and Ignition kargs
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.sh
Labels: approved, lgtm

#592 rhcos-packages: Make bootupd arch dependend
  rhcos-packages.yaml
Labels: approved, lgtm

#595 kola-denylist: disable crio.base tests for all arches
  kola-denylist.yaml
Labels: approved, lgtm

#599 kola-denylist: use string instead of list for tracker
  kola-denylist.yaml
Labels: approved, lgtm

#558 Bug 1987276: [release-4.7] Move 4.7 to RHEL 8.4
  ci/build-test-qemu.sh
  manifest.yaml
  rhcos-packages.yaml
  tests/kola/misc-ro/misc-ro.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#593 image: Switch to `ostree-format: oci`
  image.yaml
Labels: approved, lgtm

#601 Revert "image: Switch to `ostree-format: oci`"
  image.yaml
Labels: approved, lgtm
