Repository openshift/os, pull requests merged in 2022-08, with the labels that each got.

#907 docs: Add instructions to build & test SCOS
  README.md
  docs/development-scos.md
  docs/development.md
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
Labels: lgtm, approved

#924 05rhcos: add `Before=` to `rhcos-afterburn-checkin.service`
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: lgtm, approved

#925 Collection of SCOS & RHCOS 9 fixes
  extensions-c9s.yaml
  extensions-rhel-9.0.yaml
  manifest-c9s.yaml
  manifest-rhel-9.0.yaml
  overlay.d/05rhcos/usr/libexec/coreos-cryptfs
  repos/c9s.repo
Labels: lgtm, approved

#923 scos: make ext.config.files.env-godebug compatable for scos
  tests/kola/files/env-godebug
Labels: lgtm, approved

#929 common.yaml: add `crypto-policies-scripts` which provides `fips-mode-setup`
  common.yaml
Labels: lgtm, approved

#934 Bug 2114964: denylist: Skip ext.config.chrony.dhcp-propagation
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, staff-eng-approved

#938 docs: Split misc notes into its own page
  README.md
  docs/development-rhcos.md
  docs/development-scos.md
  docs/development.md
Labels: lgtm, approved

#937 CI: Partially enable RHCOS 9 & SCOS testing
  ci/prow-entrypoint.sh
  common-el9.yaml
  extensions-rhel-9.0.yaml
  manifest-c9s.yaml
  manifest-rhel-9.0.yaml
  repos/c9s.repo
Labels: lgtm, approved

#945 Bug 2116456: Revert "manifest: Pin systemd version"
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#948 manifests: include FCOS `shared-el9` manifest from `common-el9`
  common-el9.yaml
  overlay.d/15rhcos-rhel8-workarounds/statoverride
  overlay.d/25rhcos-azure-udev-rules/statoverride
  overlay.d/25rhcos-azure-udev/statoverride
Labels: lgtm, approved

#905 ci: Enable more kola tests for SCOS
  ci/prow-entrypoint.sh
  common-el9.yaml
  kola-denylist-c9s.yaml
  kola-denylist-rhel-8.6.yaml
  kola-denylist-rhel-9.0.yaml
  kola-denylist.yaml
  manifest-c9s.yaml
  overlay.d/07c9s/usr/lib/systemd/system-preset/36-scos-disabled.preset
  tests/kola/toolbox
  tests/kola/version/toolbox
Labels: lgtm, approved

#956 extensions: remove rpm-ostree build from Dockerfile
  extensions/Dockerfile
Labels: lgtm, approved

#808 image: Switch to `oci-chunked` format
  image-rhel-8.6.yaml
Labels: lgtm, approved

#955 kola-denylist: Snooze kdump.crash for s390x
  kola-denylist-c9s.yaml
  kola-denylist-rhel-8.6.yaml
  kola-denylist-rhel-9.0.yaml
Labels: lgtm, approved

#952 scos: enable some networking cases
  kola-denylist-c9s.yaml
Labels: lgtm, approved

#963 scripts/install-openshift: Use registry.ci.openshift.org
  scripts/install-openshift
Labels: approved

#959 extensions-el9: kata-containers is now available
  ci/prow-entrypoint.sh
  extensions-c9s.yaml
  extensions-rhel-9.0.yaml
  kola-denylist-c9s.yaml
  repos/c9s.repo
Labels: lgtm, approved

#961 extensions: add COSA build arg to Dockerfile
  extensions/Dockerfile
Labels: lgtm, approved

#960 rhel9: Use default `ostree-format`
  image-rhel-9.0.yaml
Labels: lgtm, approved

#962 OCPBUGS-595: overlay: Add `rhcos-selinux-policy-upgrade.service`
  overlay.d/05rhcos/usr/lib/systemd/system-preset/43-manifest-rhcos.preset
  overlay.d/05rhcos/usr/lib/systemd/system/rhcos-selinux-policy-upgrade.service
  overlay.d/05rhcos/usr/libexec/rhcos-rebuild-selinux-policy
  tests/kola/rebuild-selinux-policy/data/commonlib.sh
  tests/kola/rebuild-selinux-policy/test.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#958 Updates for variant & yumrepo support in COSA
  ci/prow-entrypoint.sh
  docs/development-rhcos.md
  docs/development-scos.md
  extensions-rhel-coreos-8.yaml
  extensions-rhel-coreos-9.yaml
  extensions-scos.yaml
  extensions.yaml
  image-rhel-coreos-8.yaml
  image-rhel-coreos-9.yaml
  image-scos.yaml
  image.yaml
  kola-denylist-c9s.yaml
  kola-denylist-rhel-8.6.yaml
  kola-denylist-rhel-9.0.yaml
  kola-denylist.yaml
  manifest-c9s.yaml
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
  manifest-rhel-coreos-8.yaml
  manifest-rhel-coreos-9.yaml
  manifest-scos.yaml
  manifest.yaml
  variant_default
  variant_rhcos
  variant_rhel-8.6
  variant_rhel-9.0
  variant_scos
Labels: lgtm, approved

#969 docs: Update build & test guides
  docs/development-rhcos.md
  docs/development-scos.md
Labels: lgtm, approved

#968 OKD-46: Fixes for non-x86_64 SCOS builds
  extensions-c9s.yaml
  repos/c9s.repo
Labels: lgtm, approved
