Repository openshift/os, pull requests merged in 2022-12, with the labels that each got.

#1066 [4.12] Change repo names to match the RHCOS repo names
  ci/prow-entrypoint.sh
  extensions-rhel-8.6.yaml
  extensions-rhel-9.0.yaml
  manifest-c9s.yaml
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1074 scripts: drop `upload-ami`
  scripts/upload-aliyun-image
  scripts/upload-ami
Labels: lgtm, approved

#1084 Revert "image*.yaml: Enable injection of OCP `machine-os` metadata by…
  image-rhel-8.6.yaml
  image-rhel-9.0.yaml
Labels: lgtm, approved

#1077 [4.10] Change repo names to match the RHCOS repo names
  extensions.yaml
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1083 OCPBUGS-4652: RHEL9: Collection of small fixes
  ci/prow-entrypoint.sh
  manifest-rhel-9.0.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1078 [4.9] Change repo names to match the RHCOS repo names
  extensions.yaml
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1082 extensions: Support variant for container image build
  extensions/Dockerfile
Labels: lgtm, approved

#1094 common-el9: Make nvmf dracut script executable
  common-el9.yaml
Labels: lgtm, approved

#1092 [rhcos-4.8/s390x] Disable luks.tang test
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1095 kola-denylist: Add a few ext.config.shared.networking
  kola-denylist.yaml
Labels: lgtm, approved

#1087 tests: Add a test that does a kernel and kernel-rt override
  tests/kola/rpm-ostree/data/commonlib.sh
  tests/kola/rpm-ostree/replace-rt-kernel
Labels: lgtm, approved

#1097 kola-denylist: Add more ext.config.shared.networking tests
  kola-denylist.yaml
Labels: lgtm, approved

#1098 OWNERS: Remove Luca
  OWNERS
Labels: lgtm, approved

#1100 denylist: Add ext.config.rpm-ostree.replace-rt-kernel
  kola-denylist.yaml
Labels: lgtm, approved

#951 ci: Enable more tests for RHCOS 9
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#1101 kola-denylist: Drop fixed tests from list
  kola-denylist.yaml
Labels: lgtm, approved

#1081 OCPBUGS-4653: [4.12] RHEL 9.0 related fixes
  ci/prow-entrypoint.sh
  common-el9.yaml
  extensions/Dockerfile
  kola-denylist.yaml
  manifest-rhel-9.0.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1001 github: Add ShellCheck workflow
  ci/prow-entrypoint.sh
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fde/module-setup.sh
  overlay.d/05rhcos/usr/libexec/coreos-cryptfs
  overlay.d/25rhcos-azure-udev/usr/lib/dracut/modules.d/25rhcos-azure-udev/module-setup.sh
  tests/kola/rebuild-selinux-policy/test.sh
  tests/kola/rpm-ostree/replace-rt-kernel
Labels: lgtm, approved

#1102 [4.12] manifest-rhel-8.6: Update repo for kernel package
  manifest-rhel-8.6.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed
