Repository openshift/os, pull requests merged in 2022-06, with the labels that each got.

#802 ci: fix prow-build.sh to fetch same repos
  ci/prow-build-test-qemu.sh
  ci/prow-build.sh
Labels: lgtm, approved

#810 ci: Also work around git checkout security check
  ci/set-openshift-user.sh
Labels: lgtm, approved

#812 ci: Use `cosa init --transient`
  ci/build-test-qemu.sh
  ci/prow-build.sh
Labels: lgtm, approved

#827 set COSA_DIR in Dockerfile
  ci/Dockerfile
  ci/prow-build-test-qemu.sh
Labels: lgtm, approved

#830 Bug 2094777: manifest: pull conmon pkg from RHAOS repo for 4.10
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#824 Add WALinuxAgent-udev package
  manifest.yaml
Labels: lgtm, approved

#811 image.yaml: Drop `random.trust_cpu=on` from default kargs
  image.yaml
Labels: lgtm, approved

#831 [4.10] ci: Work around git checkout security check
  ci/validate.sh
Labels: lgtm, approved

#832 Bug 2094799: manifest: pull conmon from RHAOS repo for 4.9
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#840 moves scripts and Dockerfiles into os repo
  ci/Dockerfile.cosa-build
  ci/Dockerfile.cosa-oci-archive
  ci/Dockerfile.layering-test
  ci/Dockerfile.machine-os-oci-content
  ci/test-qemu-firmware-uefi.sh
  ci/test-qemu-kola-upgrade.sh
  ci/test-qemu-kola.sh
  ci/test-qemu-metal.sh
  ci/test-qemu-nvme.sh
Labels: lgtm, approved

#839 Merge all Prow CI scripts into one
  ci/Dockerfile.cosa-build
  ci/Dockerfile.cosa-oci-archive
  ci/Dockerfile.layering-test
  ci/Dockerfile.machine-os-oci-content
  ci/build-test-qemu.sh
  ci/build-test.sh
  ci/prow-build-test-qemu.sh
  ci/prow-build.sh
  ci/prow-entrypoint.sh
  ci/prow-thisrepo-entrypoint.sh
  ci/set-openshift-user.sh
  ci/test-qemu-firmware-uefi.sh
  ci/test-qemu-kola-upgrade.sh
  ci/test-qemu-kola.sh
  ci/test-qemu-metal.sh
  ci/test-qemu-nvme.sh
  ci/validate.sh
Labels: lgtm, approved

#842 OWNERS: remove OWNERS file to rely on openshift/release aliases
  OWNERS
Labels: lgtm, approved

#804 tree-wide: Minor whitespace fixes
  docs/rhcos-oci-braindump.md
  live/README-devel.md
  live/isolinux/isolinux.cfg
  overlay.d/05rhcos/usr/lib/NetworkManager/conf.d/10-disable-default-plugins.conf
  overlay.d/05rhcos/usr/lib/dracut/modules.d/41rhcos-check-luks-syntax/module-setup.sh
  overlay.d/05rhcos/usr/lib/dracut/modules.d/41rhcos-check-luks-syntax/rhcos-fail-boot-for-legacy-luks-config
  overlay.d/05rhcos/usr/lib/dracut/modules.d/41rhcos-check-luks-syntax/rhcos-fail-boot-for-legacy-luks-config.service
  overlay.d/06gcp-routes/usr/sbin/gcp-routes.sh
  tests/kola/version/rhel-major-version
Labels: lgtm

#846 [release-4.11] ci: Fetch RHEL 8.6
  ci/prow-build-test-qemu.sh
Labels: lgtm, approved

#845 ci: Follow up from release changes and cleanups
  ci/Dockerfile
  ci/Dockerfile.cosa-build
  ci/Dockerfile.cosa-oci-archive
  ci/Dockerfile.layering-test
  ci/Dockerfile.machine-os-oci-content
  ci/build-test-qemu.sh
  ci/build-test.sh
  ci/prow-build-test-qemu.sh
  ci/prow-build.sh
  ci/prow-entrypoint.sh
  ci/set-openshift-user.sh
  ci/test-qemu-firmware-uefi.sh
  ci/test-qemu-kola-upgrade.sh
  ci/test-qemu-kola.sh
  ci/test-qemu-metal.sh
  ci/test-qemu-nvme.sh
  ci/validate.sh
Labels: lgtm, approved

#848 ci/prow-entrypoint: No-op `cosa init` if already initialized
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#851 ci: Add an explicitly named test entry for COSA CI
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#850 manifest: Cleanups to prepare for manifest split
  manifest.yaml
Labels: lgtm, approved

#852 Split manifest and update CI
  ci/prow-entrypoint.sh
  common.yaml
  extensions-rhel-8.6.yaml
  extensions.yaml
  manifest.yaml
  rhel-8.6.yaml
  select_version.sh
Labels: lgtm, approved

#858 kola/tests: snooze rhcos.upgrade.from-ocp-rhcos
  kola-denylist.yaml
Labels: lgtm, approved

#864 Bug 2096508: [4.9]: manifest: move runc to rhaos channel
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#866 gitmodules: use rhcos-4.11 branch from fedora-coreos-config
  .gitmodules
Labels: lgtm, approved

#867 manifests: master is now tracking 4.12
  rhel-8.6.yaml
Labels: lgtm, approved
