Repository openshift/os, pull requests merged in 2022-07, with the labels that each got.

#860 Bug 2099812: manifest: bump to openvswitch2.16
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#869 Bug 2103053: ci: Rework to merge all scripts into one
  ci/Dockerfile
  ci/build-test-qemu.sh
  ci/build-test.sh
  ci/prow-build-test-qemu.sh
  ci/prow-build.sh
  ci/prow-entrypoint.sh
  ci/prow-thisrepo-entrypoint.sh
  ci/set-openshift-user.sh
  ci/validate.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, staff-eng-approved

#878 s390x/aarch64: Deny binfmt.qemu test for now until f-c-c bump lands
  kola-denylist.yaml
Labels: lgtm, approved

#879 Add jschintag to OWNERS
  OWNERS
Labels: lgtm, approved

#763 MCO-280: extensions: Add container to serve repository with extensions
  ci/get-ocp-repo.sh
  extensions/Dockerfile
  extensions/repo-server/main.go
  extensions/test/Dockerfile
  extensions/test/ext.repo
Labels: lgtm, approved

#883 s390x: add 'genprotimg' tool
  common.yaml
Labels: lgtm, approved

#874 s390x: Cleanup after fedora-coreos-config bump
  kola-denylist.yaml
Labels: lgtm, approved

#882 ci: Remove version selection script
  ci/prow-entrypoint.sh
  select_version.sh
Labels: lgtm, approved

#880 manifest: Require `skopeo >= 2:1.7.0`
  common.yaml
Labels: lgtm, approved

#853 ci: Add all platform image builds for COSA CI test
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#885 faq: add more info about multipathing
  docs/faq.md
Labels: lgtm, approved

#887 extensions/Dockerfile: remove build arg
  extensions/Dockerfile
Labels: lgtm, approved

#886 fixes in-cluster derivation test
  tests/layering/build_helper_test.go
  tests/layering/fixtures/Dockerfile
  tests/layering/fixtures/fixtures.go
  tests/layering/fixtures/hello-world.go.fixture
  tests/layering/fixtures/hello-world.service
  tests/layering/helpers_test.go
  tests/layering/layering_test.go
Labels: lgtm, approved

#888 image.yaml: disable secure boot
  image.yaml
Labels: lgtm, approved

#892 image.yaml: change stringified boolean to boolean
  image.yaml
Labels: lgtm, approved

#894 Bug 2106058: vSphere defaults to SecureBoot on; breaks installation of out-of-tree drivers
  image.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved

#895 OWNERS: remove miabbott
  OWNERS
Labels: lgtm, approved

#898 Bug 2108320: Greatly raise `StartLimitBurst` for `rpm-ostreed.service`
  common.yaml
  overlay.d/15rhcos-rhel8-workarounds/usr/lib/systemd/system/rpm-ostreed.service.d/startlimit.conf
  tests/kola/rpm-ostree/startlimit
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#901 manifests: Prepare for variant support in COSA and add RHEL 9.0 & SCOS variants
  common.yaml
  extensions-c9s.yaml
  extensions-rhel-9.0.yaml
  image-c9s.yaml
  image-rhel-8.6.yaml
  image-rhel-9.0.yaml
  manifest-c9s.yaml
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
  manifest.yaml
  repos/c9s.repo
  variant_default
  variant_rhcos
  variant_rhel-8.6
  variant_rhel-9.0
  variant_scos
Labels: lgtm, approved

#903 `image.yaml` updates for RHEL 9
  image-c9s.yaml
  image-rhel-8.6.yaml
  image-rhel-9.0.yaml
  image.yaml
Labels: lgtm, approved

#904 rhel9: Switch to pulling toolbox from RHEL and not OCP
  manifest-rhel-9.0.yaml
Labels: lgtm, approved

#915 kola-denylist/s390x: Disable kdump test in rhcos
  kola-denylist.yaml
Labels: lgtm, approved

#911 Bug 2109546: manifest - Pin systemd version
  ci/validate.sh
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#920 OWNERS: Add Adam Piasecki (c4rt0)
  OWNERS
Labels: lgtm, approved, ok-to-test
