Repository openshift/os, pull requests merged in 2022-11, with the labels that each got.

#1044 OCPBUGS-2926: platforms: add secondary serial console on OpenStack/VirtualBox/VMware
  platforms.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1049 Revert "[#1039] pin the scos kernel to 5.14.0-168.el9"
  manifest-c9s.yaml
Labels: lgtm, approved

#1056 denylist: snooze ext.config.networking.mtu-on-bond-ignition on c9s
  kola-denylist.yaml
Labels: lgtm, approved

#1045 manifest: RHEL: Update OCP release to 4.13
  ci/prow-entrypoint.sh
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
Labels: lgtm, approved

#1060 OCPBUGS-3455: [release-4.12] gitmodules: use rhcos-4.12 branch for fedora-coreos-config
  .gitmodules
  ci/prow-entrypoint.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1030 Remove docs and some known broken symlinks
  common.yaml
Labels: lgtm, approved

#1034 tests: Remove duplicated toolbox test
  tests/kola/toolbox
Labels: lgtm, approved

#1048 image*.yaml: Enable injection of OCP `machine-os` metadata by default
  image-rhel-8.6.yaml
  image-rhel-9.0.yaml
Labels: lgtm, approved

#1071 OCPBUGS-3960: Use kernel-rt from ose repo
  extensions-rhel-8.6.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1063 OCPBUGS-3958: [release-4.12] Use kernel-rt from ose repo
  extensions-rhel-8.6.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1064 OCPBUGS-3959: [release-4.11] Use kernel-rt from ose repo
  ci/prow-entrypoint.sh
  extensions.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1067 Change repo names to match the RHCOS repo names
  ci/prow-entrypoint.sh
  extensions-rhel-8.6.yaml
  extensions-rhel-9.0.yaml
  manifest-c9s.yaml
  manifest-rhel-8.6.yaml
  manifest-rhel-9.0.yaml
Labels: lgtm, approved
