Repository openshift/os, pull requests merged in 2023-09, with the labels that each got.

#1350 azure-checkin: order checkin starting after `coreos-ignition-unique-boot`
  overlay.d/05rhcos/usr/lib/dracut/modules.d/30rhcos-afterburn-checkin/rhcos-afterburn-checkin.service
Labels: lgtm, approved

#1355 add jbtrystram as an approver
  OWNERS
Labels: lgtm, approved, ok-to-test

#1356 OCPBUGS-15843: Finish FIPS + ISO support
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1351 Add extension for 64k pages on aarch64
  extensions-c9s.yaml
  extensions-rhel-9.2.yaml
Labels: lgtm, approved, ok-to-test

#1361 docs/faq: Add RHEL mapping for 4.13
  docs/faq.md
Labels: lgtm, approved

#1359 OCPBUGS-15843: initramfs/40rhcos-fips: Workaround dracut unmounting /boot
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/module-setup.sh
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-dracut-boot-fix.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-finish.service
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, firstboot

#1331 [release-4.14] update gitmodules and bump submodule for 4.14
  .gitmodules
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1334 Update manifests and CI for 4.15
  ci/prow-entrypoint.sh
  manifest-c9s.yaml
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1364 denylist: drop ext.config.shared.kdump.crash and coreos.boot-mirror tests
  kola-denylist.yaml
Labels: lgtm, approved

#1367 image.yaml: aws; add old defaults for new fields
  image-c9s.yaml
  image-rhel-9.2.yaml
Labels: approved, do-not-merge/hold

#1370 tests/kola/trust-cpu: comment out comment even more
  tests/kola/files/trust-cpu
Labels: lgtm, approved

#1373 docs/rhcos: Add note to update cosa alias
  docs/development-rhcos.md
Labels: lgtm, approved
