Repository openshift/os, pull requests merged in 2023-11, with the labels that each got.

#1374 COS-2473: Re-enable `ostree-container-inject-openshift-cvo-labels` knob
  image-rhel-9.2.yaml
Labels: lgtm, approved, jira/valid-reference

#1394 OCPBUGS-23269: bump openvswitch to 3.1
  manifest-rhel-8.6.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1397 NO-JIRA: denylist: skip PXE tests on ppc64le
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1396 OCPBUGS-18833: google_nvme_id: sync with latest upstream version
  overlay.d/30gcp-udev-rules/usr/lib/udev/google_nvme_id
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1400 OCPBUGS-23907: Enable FIPS in live ISO
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/module-setup.sh
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-dracut-boot-fix.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-finish.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1401 NO-JIRA: denylist: skip `coreos.unique.boot.failure` on aarch64
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference
