Repository openshift/os, pull requests merged in 2023-01, with the labels that each got.

#1104 development-rhcos.md: drop 4.11 and earlier version
  docs/development-rhcos.md
Labels: lgtm, approved

#1105 Drop `.fedora-coreos-config-base`
  .fedora-coreos-config-base
Labels: lgtm, approved

#1106 kola-denylist: snooze `ext.config.shared.kdump.crash` on s390x
  kola-denylist.yaml
Labels: approved

#1011 Convert `platforms.yaml` to a symlink
  platforms.yaml
Labels: lgtm, approved

#1107 tests/kola: add trust-cpu
  tests/kola/files/data/commonlib.sh
  tests/kola/files/trust-cpu
Labels: lgtm, approved

#1115 extensions: Add a `./` to file paths to work around rpm-ostree bug
  extensions/Dockerfile
Labels: lgtm, approved

#1109 Bug 2133997: manifest: Lock multipath
  manifest-rhel-9.0.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1118 extensions: Workaround for CentOS GPG key paths
  c9s.repo
  ci/prow-entrypoint.sh
  extensions/Dockerfile
  manifest-c9s.yaml
Labels: lgtm, approved

#1123 tests/rhel-major-version: Also ignore shim-aa64
  tests/kola/version/rhel-major-version
Labels: lgtm, approved

#1122 [release-4.12] kola-denylist: 9.0: Skip package downgrade test
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1119 extensions: Use Fedora 37 as builder
  extensions/Dockerfile
Labels: lgtm, approved

#1125 [release-4.12] Revert "manifest-rhel-8.6: Update repo for kernel package"
  manifest-rhel-8.6.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1128 tests: Add `skip-console-warnings` to global kola config
  kola-denylist.yaml
Labels: lgtm, approved

#1130 Allow rhel 9 kernel to be source from the ART plashet
  manifest-rhel-9.0.yaml
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1136 rhel-9.2: Drop sig-nfv on s390x
  manifest-rhel-9.2.yaml
  openvswitch-non-s390x.yaml
Labels: lgtm, approved
