Repository openshift/os, pull requests merged in 2023-06, with the labels that each got.

#1175 Revert "tests: Add `skip-console-warnings` to global kola config"
  kola-denylist.yaml
Labels: lgtm, approved

#1305 tests/kola: delete ext.config.systemd.network-online test
  tests/kola/systemd/network-online/config.bu
  tests/kola/systemd/network-online/data/commonlib.sh
  tests/kola/systemd/network-online/test.sh
Labels: lgtm, approved

#1307 denylist: remove systemd.journal-compat
  kola-denylist.yaml
Labels: lgtm, approved

#1303 [release-4.13] Revert "tests: Add `skip-console-warnings` to global kola config"
  kola-denylist.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1314 c9s: Switch back to RPM-GPG-KEY-CentOS-SIG-Extras-SHA512
  c9s.repo
  extensions/Dockerfile
Labels: lgtm, approved

#1313 extensions/Dockerfile: Use fedora:38 as builder
  extensions/Dockerfile
Labels: lgtm, approved

#1309 kola/rpm-ostree/replace-rt-kernel: do not hardcode kernel versions
  kola-denylist.yaml
  tests/kola/rpm-ostree/replace-rt-kernel
Labels: lgtm, approved

#1320 kola/rpm-ostree/replace-rt-kernel: Only enable rt/nfv repos on x86_64
  tests/kola/rpm-ostree/replace-rt-kernel
Labels: lgtm, approved

#1321 OWNERS: offboard ashcrow and bgilbert
  OWNERS
Labels: lgtm, approved

#1322 OCPBUGS-15375: extensions: remove unused code as MCO directly uses image
  extensions/Dockerfile
  extensions/repo-server/main.go
  extensions/test/Dockerfile
  extensions/test/ext.repo
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1325 common.yaml: add comment about when to drop usermod workaround
  common.yaml
Labels: lgtm, approved
