Repository openshift/os, pull requests merged in 2023-05, with the labels that each got.

#1272 OCPBUGS-11791: overlay.d: Add 30gcp-udev-rules overlay from FCOS
  common.yaml
  overlay.d/30gcp-udev-rules
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1269 denylist: remove ext.config.kdump.crash denial
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, staff-eng-approved, backport-risk-assessed

#1256 tests: add `description` for tests
  tests/kola/afterburn/platform-id
  tests/kola/afterburn/sshkey-service
  tests/kola/console/console-login-helper-service
  tests/kola/disk/iscsi-initiatorname-service
  tests/kola/disk/nvme-compat-symlink
  tests/kola/files/check-qemu-ga
  tests/kola/files/conntrack-tools
  tests/kola/files/env-godebug
  tests/kola/files/kata-osbuilder
  tests/kola/files/localtime
  tests/kola/files/trust-cpu
  tests/kola/files/usrlocal-fixup
  tests/kola/rebuild-selinux-policy/test.sh
  tests/kola/rpm-ostree/replace-rt-kernel
  tests/kola/rpm-ostree/startlimit
  tests/kola/ssh/config
  tests/kola/systemd/journal-compat
  tests/kola/version/drop-azure-ptp
  tests/kola/version/rhaos-pkgs-match-openshift
  tests/kola/version/rhel-major-version
  tests/kola/version/rhel-matches-rhcos-build
Labels: lgtm, approved

#1275 kola: add openvswitch in hugetlbfs group test
  tests/kola/files/openvswitch-hugetlbfs-groups
Labels: lgtm, approved

#1276 kola-denylist: bump snooze for ext.config.shared.networking.nmstate
  kola-denylist.yaml
Labels: lgtm, approved

#1286 tests/trust-cpu: support v6.x kernels
  tests/kola/files/trust-cpu
Labels: lgtm, approved

#1271 OCPBUGS-12203: overlay: Inject SYSTEMD_JOURNAL_COMPRESS=LZ4 by default
  kola-denylist.yaml
  overlay.d/15rhcos-journald-backcompat/usr/lib/systemd/system/systemd-journald.service.d/rhel8-compat.conf
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1291 Fix prow CI errors for RHCOS jobs
  ci/prow-entrypoint.sh
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1289 ci: enable ci tests as we have updated to RHEL 9.2 GA repos
  ci/prow-entrypoint.sh
Labels: approved

#1293 ci: Minor cleanups
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#1288 [4.13] OCPBUGS-12206: overlay: Inject SYSTEMD_JOURNAL_COMPRESS=LZ4 by default
  ci/prow-entrypoint.sh
  overlay.d/15rhcos-journald-backcompat/usr/lib/systemd/system/systemd-journald.service.d/rhel8-compat.conf
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1292 Move non-C9S/RHEL packages to dedicated manifest
  common.yaml
  manifest-c9s.yaml
  manifest-rhel-9.2.yaml
  packages-openshift.yaml
  packages-rhcos.yaml
Labels: lgtm, approved

#1295 Update OWNERS
  OWNERS
Labels: lgtm, approved

#1294 overlay: disable iscsi.service by default
  overlay.d/07el9/usr/lib/systemd/system-preset/36-iscsid-disabled.preset
  tests/kola/systemd/network-online/config.bu
  tests/kola/systemd/network-online/data/commonlib.sh
  tests/kola/systemd/network-online/test.sh
Labels: lgtm, approved

#1297 c9s: Pull RPMs from CentOS Cloud SIG repo
  c9s.repo
  extensions/Dockerfile
  manifest-c9s.yaml
Labels: lgtm, approved

#1299 denylist: drop nmstate test denial/snooze; enable nmstate.service
  kola-denylist.yaml
  overlay.d/05rhcos/usr/lib/systemd/system-preset/43-manifest-rhcos.preset
Labels: lgtm, approved
