Repository openshift/os, pull requests merged in 2023-04, with the labels that each got.

#1234 [release-4.10] denylist: add `ext.config.shared.chrony.dhcp-propagation`
  kola-denylist.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#1235 denylist: Remove multipath.multipathd-service-fix
  kola-denylist.yaml
Labels: lgtm, approved

#1221 OCPBUGS-8008: Revert "manifest: Back to rhel toolbox"
  manifest-rhel-9.2.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1232 common.yaml: remove the workaround to add exec for `nvmf-autoconnect.sh`
  common.yaml
Labels: lgtm, approved

#1242 docs/rhcos: Update for new COSA feature
  docs/development-rhcos.md
Labels: lgtm, approved

#1238 ci: Skip Secure Boot tests for SCOS
  ci/prow-entrypoint.sh
  kola-denylist.yaml
Labels: lgtm, approved

#1203 OCPBUGS-8009: Revert to legacy toolbox
  manifest-rhel-9.2.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1243 overlay: add 30rhcos-nvme-compat-udev
  common.yaml
  overlay.d/30rhcos-nvme-compat-udev/statoverride
  overlay.d/30rhcos-nvme-compat-udev/usr/lib/dracut/modules.d/30rhcos-nvme-compat-udev/module-setup.sh
  overlay.d/30rhcos-nvme-compat-udev/usr/lib/udev/rules.d/61-persistent-storage-nvme-compat.rules
  overlay.d/README.md
  tests/kola/disk/nvme-compat-symlink
Labels: lgtm, approved

#1244 ci: Neuter `rhcos-92-build-test-*` for now
  ci/prow-entrypoint.sh
Labels: lgtm, approved

#1245 s390x/tests: Do not run nvme-nvme-compat-symlink on s390x
  tests/kola/disk/nvme-compat-symlink
Labels: lgtm, approved

#1230 OCPBUGS-11492: overlay: Inject `SYSTEMD_JOURNAL_COMPACT=0` by default
  common.yaml
  kola-denylist.yaml
  overlay.d/15rhcos-journald-backcompat/statoverride
  overlay.d/15rhcos-journald-backcompat/usr/lib/systemd/system/systemd-journald.service.d/rhel8-compat.conf
  tests/kola/systemd/data/commonlib.sh
  tests/kola/systemd/journal-compat
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1250 tests/journal-compat: Use ubi8
  tests/kola/systemd/journal-compat
Labels: lgtm, approved

#1248 OCPBUGS-11589: overlay: Inject `SYSTEMD_JOURNAL_{COMPACT,KEYED_HASH}=0`
  common.yaml
  kola-denylist.yaml
  overlay.d/15rhcos-journald-backcompat/statoverride
  overlay.d/15rhcos-journald-backcompat/usr/lib/systemd/system/systemd-journald.service.d/rhel8-compat.conf
  tests/kola/systemd/data/commonlib.sh
  tests/kola/systemd/journal-compat
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1251 OCPBUGS-11613: manifests: Use a file drop in for sshd config in EL9
  common.yaml
  overlay.d/07el9/etc/ssh/sshd_config.d/40-rhcos-defaults.conf
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1257 faq: Document running container directly for inspection
  docs/faq.md
Labels: lgtm, approved

#1255 tests: Add OpenSSH config test
  tests/kola/ssh/config
  tests/kola/ssh/data/commonlib.sh
Labels: lgtm, approved

#1260 kola-denylist: bump snooze for ext.config.shared.networking.nmstate
  kola-denylist.yaml
Labels: lgtm, approved

#1258 tests: change platform id `gce` to `gcp`
  tests/kola/afterburn/platform-id
Labels: lgtm, approved

#1263 OWNERS: remove Sohan
  OWNERS
Labels: lgtm, approved

#1261 kola-denylist: drop rhcos.network.*
  kola-denylist.yaml
Labels: lgtm, approved

#1270 docs/faq: Add 4.11 & 4.12 releases
  docs/faq.md
Labels: lgtm, approved

#1267 overlay.d: Add 30gcp-udev-rules overlay from FCOS
  common.yaml
  overlay.d/30gcp-udev-rules
Labels: lgtm, approved
