Repository openshift/os, pull requests merged in 2023-02, with the labels that each got.

#1137 faq: add entry about extensions RPMs
  docs/faq.md
Labels: lgtm, approved

#1134 Allow kernel to be sourced from the ART plashet
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1139 Move repo packages into openvswitch file
  manifest-rhel-9.2.yaml
  openvswitch-non-s390x.yaml
Labels: lgtm, approved

#1135 Allow kernel to be sourced from the ART plashet
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1138 [release-4.12] kola-denylist: Deny upgrade tests
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1140 9.2: Switch to using openvswitch from 9.0
  ci/get-ocp-repo.sh
  ci/prow-entrypoint.sh
  copr:copr.fedorainfracloud.org:amoralej:openvswitch-s390x.repo
  manifest-rhel-9.2.yaml
  openvswitch-non-s390x.yaml
  openvswitch-s390x.yaml
Labels: lgtm, approved

#1144 rhel-9.2: Add `centos-release-virt-common` on !s390x
  centos-virt.yaml
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1148 denylist: Drop snooze on `ext.config.kdump.crash` on s390x
  kola-denylist.yaml
Labels: lgtm, approved

#1145 Update development-rhcos.md
  docs/development-rhcos.md
Labels: lgtm, approved

#1150 kola: Denylist `luks.*` on ppc64le
  kola-denylist.yaml
Labels: lgtm, approved

#1142 tests: Unify format and update kola config to YAML
  tests/kola/afterburn/data/commonlib.sh
  tests/kola/afterburn/sshkey-service
  tests/kola/console/console-login-helper-service
  tests/kola/console/data/commonlib.sh
  tests/kola/disk/data/commonlib.sh
  tests/kola/disk/iscsi-initiatorname-service
  tests/kola/files/check-qemu-ga
  tests/kola/files/conntrack-tools
  tests/kola/files/env-godebug
  tests/kola/files/kata-osbuilder
  tests/kola/files/localtime
  tests/kola/files/trust-cpu
  tests/kola/files/usrlocal-fixup
  tests/kola/rpm-ostree/replace-rt-kernel
  tests/kola/version/data/commonlib.sh
  tests/kola/version/drop-azure-ptp
  tests/kola/version/rhaos-pkgs-match-openshift
  tests/kola/version/rhel-major-version
  tests/kola/version/rhel-matches-rhcos-build
Labels: lgtm, approved

#1151 extensions-rhel-9.2: Don't enable `sig-virtualization` globally
  extensions-rhel-9.2.yaml
Labels: lgtm, approved

#1155 kola-denylist: Skip luks.* tests on aarch64
  kola-denylist.yaml
Labels: lgtm, approved

#1159 Revert "kola-denylist: Run kdump test on s390x again"
  kola-denylist.yaml
Labels: lgtm, approved

#1158 [rhcos-4.12] kola-denylist: Run kdump test on s390x again
  kola-denylist.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#1161 denylist: enable `ext.config.shared.podman.rootless-systemd` test
  kola-denylist.yaml
Labels: lgtm, approved

#1163 denylists: enable networking tests
  kola-denylist.yaml
Labels: lgtm, approved

#1143 Add Adam
  OWNERS
Labels: lgtm, approved, ok-to-test

#1164 denylist: Re-enable ext.config.shared.networking.* tests
  kola-denylist.yaml
Labels: lgtm, approved, ok-to-test

#1166 faq: Document how to upgrade now outside of a cluster
  docs/faq.md
Labels: lgtm, approved

#1167 rhel-9.2: Disable centos repos by default
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1168 Add tmpfiles.d config to restore dispatcher scripts labels
  common.yaml
  overlay.d/15rhcos-networkmanager-dispatcher/statoverride
  overlay.d/15rhcos-networkmanager-dispatcher/usr/lib/tmpfiles.d/rhcos-networkmanager-dispatcher.conf
Labels: lgtm, approved

#1169 [8.6] Allow kernel to be sourced from the ART plashet
  manifest-rhel-8.6.yaml
Labels: lgtm, approved

#1147 OCPBUGS-4762: [release-4.10] manifest: bump to openvswitch2.17
  manifest.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1171 denylist: re-enable 'network-device-info' test
  kola-denylist.yaml
Labels: lgtm, approved

#1146 Bump to OVS 3.1 on RHEL9
  common-el9.yaml
  manifest-rhel-9.2.yaml
Labels: lgtm, approved

#1177 denylists: Re-enable tests
  kola-denylist.yaml
Labels: lgtm, approved

#1178 c9s: Switch to pulling directly from composes.stream.centos.org
  c9s.repo
Labels: lgtm, approved

#1180 denylist: Add `rhcos.network.*`
  kola-denylist.yaml
Labels: lgtm, approved

#1182 Revert "denylists: re-enable `luks.*` on `!x86_64`"
  kola-denylist.yaml
Labels: lgtm, approved
