Repository openshift/os, pull requests merged in 2024-01, with the labels that each got.

#1411 NO-JIRA: faq: Doc how to mount `coreos-luks-root-nocrypt`
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1413 COS-1935: overlay: include 40grub overlay from FCOS configs
  common.yaml
  overlay.d/40grub
Labels: lgtm, approved, jira/valid-reference

#1420 NO-JIRA: denylist: extend snooze for `coreos.ignition.failure`
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1416 OCPBUGS-25662: Adds ecr-image-credential-provider
  packages-openshift.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1422 NO-JIRA: manifests: add bootc to c9s and rhel-9.4 variants
  manifest-c9s.yaml
  manifest-rhel-9.4.yaml
Labels: lgtm, approved, jira/valid-reference

#1426 NO-JIRA: denylist: re-deny `iso-offline-install-iscsi.bios`
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#657 COS-2611: Use deploy-via-container
  image-c9s.yaml
  image-rhel-9.2.yaml
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1429 COS-2612: overlay: RHEL 8 workarounds cleanups
  overlay.d/05rhcos/usr/lib/systemd/system/rhcos-selinux-policy-upgrade.service
  overlay.d/05rhcos/usr/libexec/rhcos-rebuild-selinux-policy
  overlay.d/15rhcos-rhel8-workarounds/statoverride
  overlay.d/15rhcos-rhel8-workarounds/usr/lib/systemd/system/rpm-ostreed.service.d/startlimit.conf
  tests/kola/rebuild-selinux-policy/data/commonlib.sh
  tests/kola/rebuild-selinux-policy/test.sh
Labels: lgtm, approved, jira/valid-reference
