Repository openshift/os, pull requests merged in 2024-10, with the labels that each got.

#1631 NO-JIRA: okd-scos: pin clevis to 20-200.el9
  overrides-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1568 NO-JIRA: Revert "c9s: work around various SELinux issues"
  manifest-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1632 OCPBUGS-43040: overlay.d/05rhcos: Neuter coreos-luks-open for remote kdump
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fde/coreos-luks-generator
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1636 NO-JIRA: denylist: update the tracker issue for rhaos-pkgs-match-openshift
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1637 [4.17] denylist: update the tracker issue for rhaos-pkgs-match-openshift
  kola-denylist.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1638 NO-JIRA: ci: re-run failed tests and allow for success on flaky connections
  ci/prow-entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1639 NO-JIRA: ci/prow: add stubs for rhel 9.6 and c10s
  ci/prow-entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1629 COS-2959: Add rhel-9.6 and ocp-rhel-9.6 variants
  README.md
  ci/prow-entrypoint.sh
  common.yaml
  extensions-ocp-rhel-9.6.yaml
  extensions-rhel-9.6.yaml
  image-ocp-rhel-9.6.yaml
  image-rhel-9.6.yaml
  kola-denylist.yaml
  manifest-ocp-rhel-9.6.yaml
  manifest-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference

#1643 OKD-228: pin sig-cloud to release 4.18 in c9s repo
  c9s.repo
Labels: lgtm, approved, jira/valid-reference

#1645 [release-4.17] OKD-228: use sig-cloud 4.17 repo
  c9s.repo
  overrides-c9s.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1646 [release-4.16] OKD-228: use sig-cloud 4.16 repo
  c9s.repo
  overrides-c9s.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
