Repository openshift/os, pull requests merged in 2024-09, with the labels that each got.

#1600 OCPBUGS-39536: Only run rhcos-fips services if fips=1
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-dracut-boot-fix.service
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/rhcos-fips-finish.service
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1602 NO-JIRA: Add irqbalance to aarch64 builds
  common.yaml
Labels: lgtm, approved, jira/valid-reference

#1610 NO-JIRA: faq: include information about how to query openshift/os commit for release
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1563 OCPBUGS-35247: common.yaml: add subscription-manager
  common.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1605 [release-4.16] NO-JIRA: extensions/Dockerfile use fedora:38 and fedora-archive.repo
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1603 NO-JIRA: extensions/Dockerfile: use fedora-archive.repo and revert "use fedora:latest"
  extensions/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1621 COS-2940: extensions: add sysstat as RHCOS extension
  extensions-c9s.yaml
  extensions-rhel-9.4.yaml
Labels: lgtm, approved, jira/valid-reference

#1623 NO-JIRA: overlay.d/05rhcos: remove rhcos-usrlocal-selinux-fixup.service
  overlay.d/05rhcos/usr/lib/systemd/system-preset/43-manifest-rhcos.preset
  overlay.d/05rhcos/usr/lib/systemd/system/rhcos-usrlocal-selinux-fixup.service
  tests/kola/files/usrlocal-fixup
Labels: lgtm, approved, jira/valid-reference
