Repository openshift/os, pull requests merged in 2024-12, with the labels that each got.

#1663 NO-JIRA: denylist: add ext.config.shared.root-reprovision.luks.autosave-xfs
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1661 NO-JIRA: Miscellanous node image layering-related patches
  Containerfile
  group
  manifest-ocp-rhel-9.6.yaml
  packages-openshift.yaml
  passwd
  scripts/apply-manifest
Labels: lgtm, approved, jira/valid-reference

#1664 NO-JIRA: ci: add --rerun flag to `kola run`
  ci/prow-entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1667 NO-JIRA: kola-denylist: drop clevis-related entries
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1668 NO-JIRA: extension-rhel-9.6.yaml: use RHEL 9.6 content
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference

#1670 NO-JIRA: denylist: add ext.config.shared.rpm-ostree.kernel-replace
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1671 NO-JIRA: extensions: drop extensions for el-only variants
  extensions-c9s.yaml
  extensions-ocp-rhel-9.4.yaml
  extensions-ocp-rhel-9.6.yaml
  extensions-okd-c9s.yaml
  extensions-rhel-9.4.yaml
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference

#1634 OCPBUGS-43079: [release-4.17] overlay.d/05rhcos: Neuter coreos-luks-open for remote kdump
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fde/coreos-luks-generator
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1675 NO-JIRA: Remove clevis overrides for OKD
  overrides-c9s.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1683 NO-JIRA: common.yaml: disable composefs on ppc64le for now
  common.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1681 [release-4.17]:NO-JIRA: Remove clevis overrides for OKD
  overrides-c9s.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1682 NO-JIRA: extensions-ocp-rhel-9.6: add rhel-9.4-appstream for crun-wasm
  extensions-ocp-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1685 NO-JIRA: tests/replace-rt-kernel: ensure we always pick a different EVR
  tests/kola/rpm-ostree/replace-rt-kernel/test.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1688 NO-JIRA: kola-denylist: add ext.config.shared.boot.bootupd-validate
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1686 OCPBUGS-43498: pin libreswan version to 4.6 in rhcos extension
  extensions-ocp-rhel-9.4.yaml
  extensions-ocp-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#1676 NO-JIRA: packages-openshift: fix bash conditional syntax
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1690 [release-4.18] OCPBUGS-46012: pin libreswan version to 4.6 in rhcos extension
  extensions-rhel-9.4.yaml
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, do-not-merge/hold, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1695 [release-4.18] OCPBUGS-46012: pin libreswan version to 4.6 in rhcos extension
  extensions-rhel-9.4.yaml
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1693 [release-4.17] OCPBUGS-46013: pin libreswan version to 4.6 in rhcos extension
  extensions-rhel-9.4.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1674 COS-3074: ci/prow: add stubs for rhel 10
  ci/prow-entrypoint.sh
Labels: lgtm, approved, jira/valid-reference

#1689 NO-JIRA: el-only variants: drop hours and minutes from version timestamp
  manifest-c9s.yaml
  manifest-rhel-9.4.yaml
  manifest-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference

#1666 NO-JIRA: faq: add more info about multipath + iSCSI
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1698 NO-JIRA: denylist: skip `bootupd-validate` on rhel-9.4
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1700 NO-JIRA: common.yaml: disable composefs on all arches on el9
  common.yaml
Labels: lgtm, approved, jira/valid-reference

#1702 NO-JIRA: ci/get-ocp-repo.sh: add `--output-dir`
  Containerfile
  ci/get-ocp-repo.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1705 NO-JIRA: deny-list: skip `bootupd-validate` on rhel-9.4
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
