Repository openshift/os, pull requests merged in 2024-03, with the labels that each got.

#1455 OCPBUGS-30149: Revert "common.yaml: enable cliwrap"
  common.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1446 COS-2692: Prep patches for base c9s rework
  common.yaml
  manifest-c9s.yaml
  manifest-rhel-9.4.yaml
  packages-openshift.yaml
  tests/kola/files/env-godebug
  tests/kola/files/openvswitch-hugetlbfs-groups
  tests/kola/version/rhel-matches-rhcos-build
Labels: lgtm, approved, jira/valid-reference

#1457 MCO-392: Re-enable `ostree-container-inject-openshift-cvo-labels` knob
  image-c9s.yaml
  image-rhel-9.4.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1458 COS-2258: prow-entrypoint: kola arg drop `--basic-qemu-scenarios`
  ci/prow-entrypoint.sh
  docs/development-rhcos.md
  docs/development-scos.md
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1467 RHEL-29856: Temporarily use mirrored repos for c9s, and pin NetworkManager in rhel-9.4
  c9s.repo
  manifest-rhel-9.4.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1468 NO-JIRA: ci/prow-entrypoint: build extensions-container instead
  ci/prow-entrypoint.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1469 NO-JIRA: faq: add more details and examples for kernel <--> kernel-rt
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1470 NO-JIRA: faq: fix kernel-rt-modules-extra uninstall and mention kernel-64k
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1472 NO-JIRA: docs/faq: Update RHEL/RHCOS & OCP version table #1472
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference
