Repository openshift/os, pull requests merged in 2024-08, with the labels that each got.

#1556 OKD-223: Load custom SELinux rules in SCOS and workaround afterburn failures
  kola-denylist.yaml
  manifest-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1561 NO-JIRA: Various fixes for c9s variant
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
  tests/kola/rpm-ostree/replace-rt-kernel/test.sh
Labels: lgtm, approved, jira/valid-reference

#1565 NO-JIRA: extensions/Dockerfile: fix for okd-c9s variant
  extensions/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1569 OCPBUGS-38501: gitmodules: track rhcos-4.17 branch
  .gitmodules
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1562 COS-2822: port gcp-routes to nftables
  overlay.d/06gcp-routes/usr/sbin/gcp-routes.sh
Labels: lgtm, approved, jira/valid-reference

#1571 COS-2758: ITUP Cluster Migration - Use HTTPS where possible
  c9s-mirror.repo
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
Labels: lgtm, approved, jira/valid-reference

#1580 NO-JIRA: [release-4.12] ci/prow-entrypoint: tell git repo under /src is safe
  ci/prow-entrypoint.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1575 [Release 4.16] NO-JIRA: ITUP Cluster Migration - Use HTTPS where possible
  c9s-mirror.repo
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1576 [Release 4.15] NO-JIRA: ITUP Cluster Migration - Use HTTPS where possible
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1577 [Release 4.14] NO-JIRA: ITUP Cluster Migration - Use HTTPS where possible
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1578 [release 4.13] NO-JIRA: extensions/Dockerfile: Use FCOS defined fedora.repo file to set up container
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1579 [release-4.12] NO-JIRA: extensions/Dockerfile: Use FCOS defined fedora.repo file to set up container
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1585 [release-4.13] NO-JIRA: extensions/Dockerfile: bump builder to f40
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1586 [release-4.12] NO-JIRA: extensions/Dockerfile: bump builder to f40
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1583 NO-JIRA: extensions/Dockerfile: use latest Fedora to generate repo
  extensions/Dockerfile
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1574 [Release 4.17] NO-JIRA: ITUP Cluster Migration - Use HTTPS where possible
  c9s-mirror.repo
  extensions/Dockerfile
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1588 [release-4.13] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1587 [release-4.12] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1590 [release-4.15] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1592 [release-4.17] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1591 [release-4.16] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1589 [release-4.14] NO-JIRA: extensions/Dockerfile - Use fedora:latest
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1596 OCPBUGS-37875: packages-openshift.yaml: bump OVS version to 3.4
  packages-openshift.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
