Repository openshift/os, pull requests merged in 2024-05, with the labels that each got.

#1495 OCPBUGS-32927: Bump OVS version to 3.3.
  packages-openshift.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#1501 NO-JIRA: c9s: Small fixes
  c9s.repo
  ci/prow-entrypoint.sh
  image-c9s.yaml
  manifest-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1503 NO-JIRA: More prep patches for split rhel-coreos-base
  manifest-c9s.yaml
  manifest-rhel-9.4.yaml
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-reference

#1502 NO-JIRA: variants: simplify
  README.md
  c9s.repo
  ci/prow-entrypoint.sh
  extensions-c9s.yaml
  extensions-rhel-9.2.yaml
  extensions-rhel-coreos-9.yaml
  extensions-scos.yaml
  extensions.yaml
  image-rhel-9.2.yaml
  image-rhel-coreos-9.yaml
  image-scos.yaml
  image.yaml
  manifest-c9s.yaml
  manifest-rhel-9.2.yaml
  manifest-rhel-coreos-9.yaml
  manifest-scos.yaml
  manifest.yaml
  tests/kola/systemd/journal-compat
Labels: lgtm, approved, jira/valid-reference

#1506 NO-JIRA: tests/replace-rt-kernel: fix and improve
  kola-denylist.yaml
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
  tests/kola/rpm-ostree/replace-rt-kernel/data/commonlib.sh
  tests/kola/rpm-ostree/replace-rt-kernel/test.sh
Labels: lgtm, approved, jira/valid-reference

#1508 [release-4.14] tests/replace-rt-kernel: fix and improve
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
  tests/kola/rpm-ostree/replace-rt-kernel/data/commonlib.sh
  tests/kola/rpm-ostree/replace-rt-kernel/test.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1507 [release-4.15] tests/replace-rt-kernel: fix and improve
  tests/kola/rpm-ostree/replace-rt-kernel/data/c9s.repo
  tests/kola/rpm-ostree/replace-rt-kernel/data/commonlib.sh
  tests/kola/rpm-ostree/replace-rt-kernel/test.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1509 NO-JIRA: faq: clean up dynamic secondary device example
  docs/faq.md
Labels: lgtm, approved, jira/valid-reference

#1511 COS-2769: bump version to 4.17
  c9s-mirror.repo
  ci/prow-entrypoint.sh
  docs/faq.md
  extensions-rhel-9.4.yaml
  kola-denylist.yaml
  manifest-c9s.yaml
  manifest-rhel-9.4.yaml
  overrides-c9s.yaml
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-reference

#1510 OCPBUGS-34026: [release-4.16] gitmodules: track rhcos-4.16 branch
  .gitmodules
  c9s-mirror.repo
  ci/prow-entrypoint.sh
  manifest-c9s.yaml
  overrides-c9s.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1445 COS-2692: Add new variants to enable pure CentOS Stream/RHEL CoreOS builds, add Containerfile for layered OKD/OCP builds
  Containerfile
  README.md
  ci/prow-entrypoint.sh
  common.yaml
  extensions-ocp-rhel-9.4.yaml
  extensions-okd-c9s.yaml
  extensions.yaml
  image-ocp-rhel-9.4.yaml
  image-okd-c9s.yaml
  image.yaml
  manifest-c9s.yaml
  manifest-ocp-rhel-9.4.yaml
  manifest-okd-c9s.yaml
  manifest-rhel-9.4.yaml
  manifest.yaml
  scripts/apply-manifest
  tests/kola/version/rhel-major-version
  tests/kola/version/rhel-matches-rhcos-build
Labels: lgtm, approved, jira/valid-reference
