Repository openshift/os, pull requests merged in 2025-03, with the labels that each got.

#1757 OCPBUGS-52363: ci/get-ocp-repo.sh: Fixes for scos to accomodate building images in CI
  Containerfile
  ci/get-ocp-repo.sh
  extensions/Dockerfile
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1761 NO-JIRA: Containerfile: add metadata in last layer of node image
  Containerfile
  scripts/generate-metadata
Labels: lgtm, approved, jira/valid-reference

#1763 [release-4.14] OCPBUGS-52577: pin libreswan version to 4.6 in rhcos extension
  extensions-c9s.yaml
  extensions-rhel-9.2.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1764 NO-JIRA: scripts/generate-metadata: make epoch field a string
  scripts/generate-metadata
Labels: lgtm, approved, jira/valid-reference

#1765 OCPBUGS-48614: Move ose-aws-ecr-image-credential-provider to CoreOS base
  common.yaml
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1770 NO-JIRA: ci/get-ocp-repo.sh: pull in mirror repos when building scos
  ci/get-ocp-repo.sh
  extensions-okd-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1769 NO-JIRA: ci/prow-entrypoint: skip pxe-offline-install.rootfs-appended.bios for…
  ci/prow-entrypoint.sh
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1773 NO-JIRA: Move ose-aws-ecr-image-credential-provider to rhel-9.6 only
  common.yaml
  manifest-rhel-9.6.yaml
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-reference

#1772 NO-JIRA: Various patches to build extensions container using `podman build` in production
  ci/get-ocp-repo.sh
  ci/prow-entrypoint.sh
  extensions/Dockerfile
  scripts/generate-metadata
Labels: lgtm, approved, jira/valid-reference

#1774 OCPBUGS-53384: [release-4.15] packages-openshift.yaml: bump OVS version to 3.3
  packages-openshift.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
