Repository openshift/os, pull requests merged in 2025-01, with the labels that each got.

#1701 COS-3063: Adding the needed packages for Kubesan and the kSAN Storage Operator
  extensions-ocp-rhel-9.6.yaml
  extensions-okd-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1708 NO-JIRA:OKD: Move sig-cloud to 4.19
  c9s.repo
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1716 NO-JIRA: change default variant to ocp-rhel-9.6
  README.md
  extensions.yaml
  image.yaml
  manifest-okd-c9s.yaml
  manifest.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1714 NO-JIRA: manifest-ocp-rhel-9.6: get toolbox from ART plashet
  manifest-ocp-rhel-9.4.yaml
  manifest-ocp-rhel-9.6.yaml
  packages-rhcos.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1715 COS-3076: kola-denylist.yaml: disable ext.config.composefs.enabled on el9
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1717 COS-3076: kola-denylist.yaml: add missing 'shared' to composefs.enabled testname
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1703 NO-JIRA: ci/prow: test on RHEL 9.6
  ci/get-ocp-repo.sh
  ci/prow-entrypoint.sh
  extensions-ocp-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1721 NO-JIRA: denylist: snooze `ostree.sync` on `s390x`
  kola-denylist.yaml
Labels: approved, jira/valid-reference

#1727 NO-JIRA: kola-denylist: drop ext.config.shared.rpm-ostree.kernel-replace
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1719 COS-2873: extensions/Dockerfile: Get extensions rpm list
  extensions/Dockerfile
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
