Repository openshift/os, pull requests merged in 2025-02, with the labels that each got.

#1732 [release-4.18] OCPBUGS-49833: Backport extensions/Dockerfile: Get extensions rpm list
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1737 NO-JIRA: extensions: include release and arch in extensions.json
  extensions/Dockerfile
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1734 [release-4.17] OCPBUGS-49834: Backport extensions/Dockerfile: Get extensions rpm list
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1741 NO-JIRA: manifest-rhel-9.6: add early kernel repo
  manifest-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1740 NO-JIRA: Containerfile: use secrets API for yum repo injection
  Containerfile
  packages-openshift.yaml
  scripts/apply-manifest
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1742 NO-JIRA: rework manifests and drop mentions of 9.4
  README.md
  ci/prow-entrypoint.sh
  common.yaml
  extensions-ocp-rhel-9.4.yaml
  image-c9s.yaml
  image-ocp-rhel-9.4.yaml
  image-rhel-9.4.yaml
  image-rhel-9.6.yaml
  manifest-el9-shared.yaml
  manifest-ocp-rhel-9.4.yaml
  manifest-rhel-9.4.yaml
  zram-no-defaults.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1736 [release-4.16] OCPBUGS-49835: Backport extensions/Dockerfile: Get extensions rpm list
  extensions/Dockerfile
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1735 NO-JIRA: common.yaml: re-enable composefs on el9
  kola-denylist.yaml
  manifest-el9-shared.yaml
  packages-openshift.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1743 OCPEDGE-1493: extensions: add 2no-ha required by Two Node OpenShift
  extensions-ocp-rhel-9.6.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-reference, acknowledge-critical-fixes-only

#1753 NO-JIRA: denylist: enable `ostree.sync` and disable on c10s
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1755 NO-JIRA: denylist: remove c9s fips.* entry
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference
