Repository openshift/os, pull requests merged in 2025-04, with the labels that each got.

#1781 NO-JIRA: OWNERS - Add user as approver
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1782 NO-JIRA: denylist: re enable kdump tests
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1783 NO-JIRA: Add jcapiitao to the OWNERS file
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1771 SDN-5544: Unpin libreswan version
  extensions-ocp-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1785 NO-JIRA: Drop oscontainer.yaml
  oscontainer.yaml
Labels: lgtm, approved, jira/valid-reference

#1788 NO-JIRA: Prep patches for #1780
  common.yaml
  manifest-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1789 c9s.repo: hardcode x86_64 in baseurl
  c9s.repo
Labels: approved

#1780 NO-JIRA: Switch layered build to `treefile-apply`, drain `get-ocp-repo.sh`
  Containerfile
  README.md
  build-node-image.sh
  c9s-mirror.repo
  c9s.repo
  ci/get-ocp-repo.sh
  ci/prow-entrypoint.sh
  extensions-ocp-rhel-9.6.yaml
  extensions-okd-c9s.yaml
  extensions/Dockerfile
  extensions/build.sh
  image-okd-c9s.yaml
  manifest-c9s.yaml
  manifest-okd-c9s.yaml
  manifest-rhel-9.6.yaml
  packages-openshift.yaml
  scripts/apply-manifest
Labels: lgtm, approved, jira/valid-reference

#1784 OCPBUGS-52293: extensions: make rhel-9.4-appstream global
  extensions-ocp-rhel-9.6.yaml
  extensions-okd-c9s.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1791 NO-JIRA: extensions-ocp-rhel-9.6.yaml: add back in rhel-9.6-server-ose-4.19 repo
  extensions-ocp-rhel-9.6.yaml
  extensions-okd-c10s.yaml
  extensions-okd-c9s.yaml
Labels: lgtm, approved, jira/valid-reference

#1776 COS-3126: overlay.d: replace 25rhcos-azure-udev
  manifest-el9-shared.yaml
  overlay.d/25rhcos-azure-udev/usr/lib/dracut/modules.d/25rhcos-azure-udev/module-setup.sh
  overlay.d/25rhcos-azure-udev/usr/lib/udev/rules.d/80-azure-disk.rules
  overlay.d/README.md
Labels: lgtm, approved, jira/valid-reference

#1797 NO-JIRA: c10s.repo: use x86_64 extras-common URL for all arch
  c10s.repo
Labels: lgtm, approved, jira/valid-reference

#1798 NO-JIRA: denylist: update iso mpath denials
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1799 NO-JIRA: denylist: ext.config.rpm-ostree.replace-rt-kernel for c10s on ppc64le
  kola-denylist.yaml
Labels: lgtm, approved, jira/valid-reference

#1795 [release-4.18] OCPBUGS-54594: update bootloader on aarch64 systems
  overlay.d/05rhcos/usr/lib/systemd/system-preset/43-manifest-rhcos.preset
  overlay.d/05rhcos/usr/lib/systemd/system/coreos-bootupctl-update-aarch64.service
  overlay.d/05rhcos/usr/libexec/coreos-update-bootloader
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1805 NO-JIRA: manifest-el9-shared: Update comment for composefs=maybe
  manifest-el9-shared.yaml
Labels: lgtm, approved, jira/valid-reference
