Repository openshift/os, pull requests merged in 2025-07, with the labels that each got.

#1832 NO-JIRA: denylist: add ostree.remote to denylist for 4.15
  kola-denylist.yaml
Labels: approved, jira/valid-reference

#1831 NO-JIRA: denylist: add ostree.remote to denylist for 4.12
  kola-denylist.yaml
Labels: jira/valid-reference

#1837 OCPBUGS-47495: 40rhcos-fips: include fips.so in initrd
  overlay.d/05rhcos/usr/lib/dracut/modules.d/40rhcos-fips/module-setup.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1843 COS-3424: Revert ostree.remote snooze - 4.15
  kola-denylist.yaml
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1812 NO-JIRA: Add PeaceRebel (Bipin) to approvers list
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1848 NO-JIRA: extensions-rhel-9.4: Unpin `libreswan`
  extensions-rhel-9.4.yaml
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1849 OCPBUGS-59303: Revert "extensions-rhel-9.{4,6}: unpin libreswan"
  extensions-rhel-9.4.yaml
  extensions-rhel-9.6.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
